// This file is autogenerated, please don't change manually 
"use strict";
"require baseclass";
"require dom";
"require ui";
"require rpc";
"require uci";
"require fs";

// src/constants.ts
var VERSION = "__COMPILED_VERSION_VARIABLE__";
var PKG = "__PKG_NAME__";
var BRAND = "__BRAND_NAME__";
var ACCENT = "__ACCENT__";
var SUPPORT_URL = "__SUPPORT_URL__";
var DOCS_URL = "__DOCS_URL__";
var DASHBOARD = "__DASHBOARD__";
var API_PORT = 9090;
var TPROXY_PORT = 7894;
var FAKEIP_RANGE = "198.18.0.0/16";
var DNS_TYPE_OPTIONS = {
  udp: "UDP (plain 53)",
  doh: "DNS over HTTPS",
  dot: "DNS over TLS"
};
var DNS_SERVER_OPTIONS = {
  "1.1.1.1": "1.1.1.1 (Cloudflare)",
  "8.8.8.8": "8.8.8.8 (Google)",
  "9.9.9.9": "9.9.9.9 (Quad9)",
  "dns.adguard-dns.com": "dns.adguard-dns.com (AdGuard Default)",
  "unfiltered.adguard-dns.com": "unfiltered.adguard-dns.com (AdGuard Unfiltered)",
  "family.adguard-dns.com": "family.adguard-dns.com (AdGuard Family)"
};
var BOOTSTRAP_DNS_SERVER_OPTIONS = {
  "1.1.1.1": "1.1.1.1 (Cloudflare)",
  "1.0.0.1": "1.0.0.1 (Cloudflare)",
  "8.8.8.8": "8.8.8.8 (Google)",
  "8.8.4.4": "8.8.4.4 (Google)",
  "9.9.9.9": "9.9.9.9 (Quad9)",
  "77.88.8.8": "77.88.8.8 (Yandex)"
};
var UPDATE_INTERVAL_OPTIONS = {
  "1h": "Every hour",
  "3h": "Every 3 hours",
  "12h": "Every 12 hours",
  "1d": "Every day",
  "3d": "Every 3 days"
};
var PROXY_TYPE_OPTIONS = {
  url: "Single URL",
  selector: "Selector (manual choice)",
  urltest: "URL test (auto-fastest)",
  raw: "Raw outbound JSON"
};

// src/brand.ts
var TOKEN_RE = /^__[A-Z0-9_]+__$/;
function resolved(value, fallback) {
  return TOKEN_RE.test(value) ? fallback : value;
}
var FALLBACK = {
  name: "Router",
  accent: "#2e7d32",
  supportUrl: "",
  docsUrl: ""
};
function brandInfo() {
  return {
    name: resolved(BRAND, FALLBACK.name),
    accent: resolved(ACCENT, FALLBACK.accent),
    supportUrl: resolved(SUPPORT_URL, FALLBACK.supportUrl),
    docsUrl: resolved(DOCS_URL, FALLBACK.docsUrl)
  };
}

// src/validators.ts
var PORT_MIN = 1;
var PORT_MAX = 65535;
function ok(scheme) {
  return { valid: true, scheme };
}
function fail(scheme, error) {
  return scheme ? { valid: false, scheme, error } : { valid: false, error };
}
function isValidPort(value) {
  if (!/^\d+$/.test(value)) return false;
  const n = Number(value);
  return n >= PORT_MIN && n <= PORT_MAX;
}
function isValidPortSpec(value) {
  const entries = value.split(",");
  if (entries.length === 0) return false;
  return entries.every((entry) => {
    if (!entry) return false;
    if (entry.indexOf("-") < 0) return isValidPort(entry);
    const parts = entry.split("-");
    if (parts.length !== 2) return false;
    if (!isValidPort(parts[0]) || !isValidPort(parts[1])) return false;
    return Number(parts[0]) <= Number(parts[1]);
  });
}
function parseHostPort(hostPort) {
  const clean = hostPort.replace(/\/+$/, "");
  const idx = clean.lastIndexOf(":");
  if (idx < 0) return { host: clean, port: "" };
  return { host: clean.slice(0, idx), port: clean.slice(idx + 1) };
}
function safeDecode(value) {
  try {
    return decodeURIComponent(value);
  } catch {
    return value;
  }
}
function parseQuery(query) {
  const out = {};
  if (!query) return out;
  for (const pair of query.split("&")) {
    if (!pair) continue;
    const eq = pair.indexOf("=");
    const key = eq < 0 ? pair : pair.slice(0, eq);
    const value = eq < 0 ? "" : pair.slice(eq + 1);
    if (key) out[safeDecode(key)] = safeDecode(value);
  }
  return out;
}
function validateVlessUrl(url) {
  const scheme = "vless";
  if (!url.startsWith("vless://"))
    return fail(scheme, _("VLESS URL must start with vless://"));
  if (/\s/.test(url))
    return fail(scheme, _("VLESS URL must not contain whitespace"));
  const [userHostPort] = url.slice("vless://".length).split("#")[0].split("?");
  const at = userHostPort.lastIndexOf("@");
  if (at < 0)
    return fail(scheme, _("VLESS URL is missing the UUID@server separator"));
  const uuid = userHostPort.slice(0, at);
  if (!uuid) return fail(scheme, _("VLESS URL is missing the UUID"));
  const { host, port } = parseHostPort(userHostPort.slice(at + 1));
  if (!host) return fail(scheme, _("VLESS URL is missing the server host"));
  if (!port) return fail(scheme, _("VLESS URL is missing the port"));
  if (!isValidPort(port))
    return fail(scheme, _("VLESS URL has an invalid port"));
  return ok(scheme);
}
function validateShadowsocksUrl(url) {
  const scheme = "ss";
  const prefix = url.startsWith("shadowsocks://") ? "shadowsocks://" : url.startsWith("ss://") ? "ss://" : "";
  if (!prefix) return fail(scheme, _("Shadowsocks URL must start with ss://"));
  if (/\s/.test(url))
    return fail(scheme, _("Shadowsocks URL must not contain whitespace"));
  const body = url.slice(prefix.length).split("#")[0].split("?")[0];
  const at = body.lastIndexOf("@");
  if (at < 0)
    return fail(
      scheme,
      _("Shadowsocks URL is missing the credentials@server separator")
    );
  const userinfo = body.slice(0, at);
  if (!userinfo)
    return fail(scheme, _("Shadowsocks URL is missing the credentials"));
  const { host, port } = parseHostPort(body.slice(at + 1));
  if (!host)
    return fail(scheme, _("Shadowsocks URL is missing the server host"));
  if (!port) return fail(scheme, _("Shadowsocks URL is missing the port"));
  if (!isValidPort(port))
    return fail(scheme, _("Shadowsocks URL has an invalid port"));
  return ok(scheme);
}
function validateTrojanUrl(url) {
  const scheme = "trojan";
  if (!url.startsWith("trojan://"))
    return fail(scheme, _("Trojan URL must start with trojan://"));
  if (/\s/.test(url))
    return fail(scheme, _("Trojan URL must not contain whitespace"));
  const [userHostPort] = url.slice("trojan://".length).split("#")[0].split("?");
  const at = userHostPort.lastIndexOf("@");
  if (at < 0)
    return fail(
      scheme,
      _("Trojan URL is missing the password@server separator")
    );
  const password = userHostPort.slice(0, at);
  if (!password) return fail(scheme, _("Trojan URL is missing the password"));
  const { host, port } = parseHostPort(userHostPort.slice(at + 1));
  if (!host) return fail(scheme, _("Trojan URL is missing the server host"));
  if (!port) return fail(scheme, _("Trojan URL is missing the port"));
  if (!isValidPort(port))
    return fail(scheme, _("Trojan URL has an invalid port"));
  return ok(scheme);
}
function validateHysteria2Url(url) {
  const scheme = "hysteria2";
  const isLong = url.startsWith("hysteria2://");
  const isShort = url.startsWith("hy2://");
  if (!isLong && !isShort)
    return fail(
      scheme,
      _("Hysteria2 URL must start with hysteria2:// or hy2://")
    );
  if (/\s/.test(url))
    return fail(scheme, _("Hysteria2 URL must not contain whitespace"));
  const prefix = isLong ? "hysteria2://" : "hy2://";
  const [main, queryString] = url.slice(prefix.length).split("#")[0].split("?");
  const at = main.lastIndexOf("@");
  if (at < 0)
    return fail(
      scheme,
      _("Hysteria2 URL is missing the password@server separator")
    );
  const password = main.slice(0, at);
  if (!password)
    return fail(scheme, _("Hysteria2 URL is missing the password"));
  const { host, port } = parseHostPort(main.slice(at + 1));
  if (!host) return fail(scheme, _("Hysteria2 URL is missing the server host"));
  const params = parseQuery(queryString);
  const portSpec = params.mport || port;
  if (!portSpec) return fail(scheme, _("Hysteria2 URL is missing the port"));
  if (!isValidPortSpec(portSpec))
    return fail(scheme, _("Hysteria2 URL has an invalid port"));
  if (params.obfs && params.obfs !== "none" && params.obfs !== "salamander")
    return fail(scheme, _("Hysteria2 URL has an unsupported obfs type"));
  return ok(scheme);
}
function validateSocksUrl(url) {
  const scheme = "socks";
  if (!/^socks5?:\/\//.test(url))
    return fail(scheme, _("SOCKS URL must start with socks:// or socks5://"));
  if (/\s/.test(url))
    return fail(scheme, _("SOCKS URL must not contain whitespace"));
  const body = url.replace(/^socks5?:\/\//, "").split("#")[0].split("?")[0];
  const at = body.lastIndexOf("@");
  if (at >= 0) {
    const username = body.slice(0, at).split(":")[0];
    if (!username) return fail(scheme, _("SOCKS URL is missing the username"));
  }
  const { host, port } = parseHostPort(at >= 0 ? body.slice(at + 1) : body);
  if (!host) return fail(scheme, _("SOCKS URL is missing the server host"));
  if (!port) return fail(scheme, _("SOCKS URL is missing the port"));
  if (!isValidPort(port))
    return fail(scheme, _("SOCKS URL has an invalid port"));
  return ok(scheme);
}
function validateProxyUrl(url) {
  const trimmed = (url || "").trim();
  if (trimmed === "") return fail(void 0, _("Proxy URL is empty"));
  if (trimmed.startsWith("vless://")) return validateVlessUrl(trimmed);
  if (trimmed.startsWith("ss://") || trimmed.startsWith("shadowsocks://"))
    return validateShadowsocksUrl(trimmed);
  if (trimmed.startsWith("trojan://")) return validateTrojanUrl(trimmed);
  if (trimmed.startsWith("hysteria2://") || trimmed.startsWith("hy2://"))
    return validateHysteria2Url(trimmed);
  if (/^socks5?:\/\//.test(trimmed)) return validateSocksUrl(trimmed);
  return fail(
    void 0,
    _(
      "Proxy URL must start with vless://, ss://, trojan://, hysteria2://, hy2:// or socks://"
    )
  );
}

// src/rpc.ts
var callVersion = rpc.declare({
  object: "luci.__PKG_NAME__",
  method: "version",
  expect: { "": {} }
});
var callLists = rpc.declare({
  object: "luci.__PKG_NAME__",
  method: "lists",
  expect: { "": {} }
});
var callDiag = rpc.declare({
  object: "luci.__PKG_NAME__",
  method: "diag",
  params: ["check"],
  expect: { "": {} }
});
var callLogs = rpc.declare({
  object: "luci.__PKG_NAME__",
  method: "logs",
  params: ["lines"],
  expect: { "": {} }
});
var callApi = rpc.declare({
  object: "luci.__PKG_NAME__",
  method: "api",
  params: ["method", "path", "query", "body"],
  expect: { "": {} }
});
var callDashboardInfo = rpc.declare({
  object: "luci.__PKG_NAME__",
  method: "dashboard_info",
  expect: { "": {} }
});
var callRcList = rpc.declare({
  object: "rc",
  method: "list",
  params: ["name"],
  expect: { "": {} }
});
var callRcInit = rpc.declare({
  object: "rc",
  method: "init",
  params: ["name", "action"],
  expect: { "": {} }
});
function version() {
  return callVersion();
}
function lists() {
  return callLists();
}
function diag(check) {
  return callDiag(check);
}
function logs(lines) {
  return callLogs(lines);
}
function api(method, path, query, body) {
  return callApi(method, path, query, body);
}
function dashboardInfo() {
  return callDashboardInfo();
}
async function serviceStatus() {
  const list = await callRcList("__PKG_NAME__");
  return Boolean(list && list["__PKG_NAME__"] && list["__PKG_NAME__"].running);
}
function serviceAction(action) {
  return callRcInit("__PKG_NAME__", action);
}

// src/mihomo.ts
async function rpcApi(method, path, opts = {}) {
  const query = opts.query ? new URLSearchParams(opts.query).toString() : "";
  const body = opts.body != null ? JSON.stringify(opts.body) : "";
  const res = await api(method, path, query, body);
  return res;
}
function getProxies() {
  return rpcApi("GET", "/proxies");
}
function getMihomoVersion() {
  return rpcApi("GET", "/version");
}
function selectProxy(group, name) {
  return rpcApi("PUT", `/proxies/${encodeURIComponent(group)}`, {
    body: { name }
  });
}
function wsBase(info) {
  const proto = info && info.https ? "wss" : "ws";
  const host = typeof window !== "undefined" && window.location ? window.location.hostname : "127.0.0.1";
  const port = info && info.port || API_PORT;
  return `${proto}://${host}:${port}`;
}
async function wsStream(endpoint, onMessage, onError) {
  const noop = { close() {
  } };
  if (typeof WebSocket === "undefined") return noop;
  try {
    const info = await dashboardInfo();
    const secret = info && info.secret || "";
    const url = `${wsBase(info)}${endpoint}?token=${encodeURIComponent(secret)}`;
    const sock = new WebSocket(url);
    sock.onmessage = (ev) => {
      try {
        onMessage(JSON.parse(String(ev.data)));
      } catch (e) {
        if (onError) onError(e);
      }
    };
    sock.onerror = (ev) => {
      if (onError) onError(ev);
    };
    return {
      close() {
        try {
          sock.close();
        } catch {
        }
      }
    };
  } catch (e) {
    if (onError) onError(e);
    return noop;
  }
}

// src/dashboard.ts
var IDS = {
  root: "__PKG_NAME__-dashboard",
  status: "__PKG_NAME__-dashboard-status",
  statusText: "__PKG_NAME__-dashboard-status-text",
  widgets: "__PKG_NAME__-dashboard-widgets"
};
var statusTimer = null;
var styles = `
.__PKG_NAME__-card {
  --accent: __ACCENT__;
  border: 1px solid var(--border-color-medium, rgba(0,0,0,.12));
  border-radius: 8px;
  padding: 20px;
  max-width: 640px;
  margin-top: 10px;
}
.__PKG_NAME__-card__header {
  display: flex;
  align-items: center;
  gap: 10px;
  margin-bottom: 6px;
}
.__PKG_NAME__-card__badge {
  color: #fff;
  background: var(--accent);
  border-radius: 4px;
  padding: 2px 8px;
  font-weight: 700;
  font-size: 12px;
  letter-spacing: .02em;
}
.__PKG_NAME__-card__title {
  margin: 0;
  font-size: 18px;
}
.__PKG_NAME__-card__version {
  margin-left: auto;
  opacity: .6;
  font-size: 12px;
}
.__PKG_NAME__-card__desc {
  margin: 6px 0 14px;
  opacity: .85;
}
.__PKG_NAME__-card__status {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 14px;
}
.__PKG_NAME__-status-dot {
  width: 10px;
  height: 10px;
  border-radius: 50%;
  background: var(--border-color-high, #999);
  flex: 0 0 auto;
}
.__PKG_NAME__-status-dot--up { background: var(--success-color-medium, #2e7d32); }
.__PKG_NAME__-status-dot--down { background: var(--error-color-medium, #c62828); }
.__PKG_NAME__-card__actions {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
}
.__PKG_NAME__-card__actions .btn { text-decoration: none; }
.__PKG_NAME__-card__actions .__PKG_NAME__-btn--primary {
  background: var(--accent);
  border-color: var(--accent);
  color: #fff;
}
.__PKG_NAME__-widgets { margin-top: 16px; }
`;
function buildDashboardUrl(info) {
  const proto = info && info.https ? "https" : "http";
  const host = typeof window !== "undefined" && window.location ? window.location.hostname : "127.0.0.1";
  const port = info && info.port || API_PORT;
  const ui2 = info && info.ui_name ? info.ui_name : DASHBOARD;
  const secret = info && info.secret ? info.secret : "";
  const query = new URLSearchParams({
    hostname: host,
    host,
    port: String(port),
    secret
  }).toString();
  return `${proto}://${host}:${port}/ui/${ui2}/?${query}`;
}
async function openDashboard(ev) {
  if (ev) ev.preventDefault();
  try {
    const info = await dashboardInfo();
    const url = buildDashboardUrl(info);
    setTimeout(() => window.open(url, "_blank", "noopener"), 0);
  } catch (e) {
    if (typeof ui !== "undefined" && ui.addNotification)
      ui.addNotification(
        null,
        E("p", {}, _("Failed to resolve the dashboard address")),
        "danger"
      );
    if (typeof L !== "undefined" && L.error) L.error(e);
  }
}
function paintStatus(running) {
  const dot = document.getElementById(IDS.status);
  const text = document.getElementById(IDS.statusText);
  if (dot) {
    dot.className = "__PKG_NAME__-status-dot " + (running ? "__PKG_NAME__-status-dot--up" : "__PKG_NAME__-status-dot--down");
  }
  if (text)
    text.textContent = running ? _("Service running") : _("Service stopped");
}
async function refreshStatus() {
  if (!document.getElementById(IDS.status)) return;
  let running = false;
  try {
    running = await serviceStatus();
  } catch {
    running = false;
  }
  paintStatus(running);
}
function render() {
  const brand = brandInfo();
  return E("div", { class: "__PKG_NAME__-card", id: IDS.root }, [
    E("div", { class: "__PKG_NAME__-card__header" }, [
      E("span", { class: "__PKG_NAME__-card__badge" }, brand.name),
      E("h3", { class: "__PKG_NAME__-card__title" }, _("Dashboard")),
      E("span", { class: "__PKG_NAME__-card__version" }, VERSION)
    ]),
    E(
      "p",
      { class: "__PKG_NAME__-card__desc" },
      _(
        "Monitor proxies, traffic and connections in the mihomo web dashboard."
      )
    ),
    E("div", { class: "__PKG_NAME__-card__status" }, [
      E("span", {
        class: "__PKG_NAME__-status-dot",
        id: IDS.status
      }),
      E("span", { id: IDS.statusText }, _("Checking service status\u2026"))
    ]),
    E("div", { class: "__PKG_NAME__-card__actions" }, [
      E(
        "button",
        {
          type: "button",
          class: "btn cbi-button cbi-button-action __PKG_NAME__-btn--primary",
          click: openDashboard
        },
        _("Open dashboard")
      ),
      brand.docsUrl ? E(
        "a",
        {
          class: "btn cbi-button",
          href: brand.docsUrl,
          target: "_blank",
          rel: "noopener"
        },
        _("Documentation")
      ) : E("span"),
      brand.supportUrl ? E(
        "a",
        {
          class: "btn cbi-button",
          href: brand.supportUrl,
          target: "_blank",
          rel: "noopener"
        },
        _("Support")
      ) : E("span")
    ]),
    // Reserved for future live widgets (traffic / connections / memory).
    // Hidden and empty in phase 1 — no streaming is started to render the card.
    E("div", {
      id: IDS.widgets,
      class: "__PKG_NAME__-widgets",
      style: "display:none"
    })
  ]);
}
function initController() {
  void refreshStatus();
  if (statusTimer === null) {
    statusTimer = setInterval(() => void refreshStatus(), 1e4);
  }
}
function destroy() {
  if (statusTimer !== null) {
    clearInterval(statusTimer);
    statusTimer = null;
  }
}
var DashboardTab = {
  styles,
  render,
  initController,
  destroy,
  openDashboard
};

// src/main.ts
if (typeof structuredClone !== "function")
  globalThis.structuredClone = (obj) => JSON.parse(JSON.stringify(obj));
return baseclass.extend({
  ACCENT,
  API_PORT,
  BOOTSTRAP_DNS_SERVER_OPTIONS,
  BRAND,
  DASHBOARD,
  DNS_SERVER_OPTIONS,
  DNS_TYPE_OPTIONS,
  DOCS_URL,
  DashboardTab,
  FAKEIP_RANGE,
  PKG,
  PROXY_TYPE_OPTIONS,
  SUPPORT_URL,
  TPROXY_PORT,
  UPDATE_INTERVAL_OPTIONS,
  VERSION,
  api,
  brandInfo,
  dashboardInfo,
  diag,
  getMihomoVersion,
  getProxies,
  lists,
  logs,
  rpcApi,
  selectProxy,
  serviceAction,
  serviceStatus,
  styles,
  validateHysteria2Url,
  validateProxyUrl,
  validateShadowsocksUrl,
  validateSocksUrl,
  validateTrojanUrl,
  validateVlessUrl,
  version,
  wsStream
});
