import { defineConfig } from 'tsup';
import fs from 'fs';
import path from 'path';

// The bundle is a LuCI baseclass module. tsup/esbuild emits a trailing
// `export { ... }`; onSuccess rewrites it into `return baseclass.extend({ ... })`
// which is exactly what LuCI's module loader expects. __TOKEN__ string literals
// are left intact so one build serves every brand (the luci-app Makefile seds
// them at install time).
const OUT_DIR = '../packages/luci-app-daypass/htdocs/luci-static/resources/view/app';

export default defineConfig({
    entry: ['src/main.ts'],
    format: ['esm'], // let tsup generate `export { ... }`
    outDir: OUT_DIR,
    outExtension: () => ({ js: '.js' }),
    dts: false,
    clean: false,
    sourcemap: false,
    banner: {
        js: `// This file is autogenerated, please don't change manually \n"use strict";`,
    },
    esbuildOptions(options) {
        options.legalComments = 'none';
    },
    onSuccess: () => {
        const file = path.join(OUT_DIR, 'main.js');
        let code = fs.readFileSync(file, 'utf8');

        code = code.replace(/export\s*{([\s\S]*?)}/, (match, group) => {
            return `return baseclass.extend({${group}})`;
        });

        fs.writeFileSync(file, code, 'utf8');
        console.log(`✅ Patched LuCI build: ${file}`);
    },
});
